Dada una lista de palabras se pide retornar la lista pero intercalando las
palabras desde el final y desde el inicio. 
 
Ejemplo: Hoy puede que llueva, se retorna llueva Hoy que puede.

tds -> oracion										print(oracion.x)
oracion -> palara_inicio ' ' oracion ' ' palabra_final      oracion.x = palabra_final.x || palabra_inicio.x ||  oracion.x
oracion -> E                                      oracion.x = " "
oracion -> palabra                                  oracion.x = palabra.x 


palabra_inicio -> palabra                           palabra_inicio.x = palabra.x
palabra_final -> palabra                            palabra_final.x = palabra.x
palabra_final -> " "                                palabra_final.x = " "


palabra -> palabra letra                            palabra.x = palabra.x || letra.x
palabra -> letra                                    palabra.x = letra.x

letra ->  a                                         letra.x = "a"                                       
letra ->  b                                         letra.x = "b"                          
letra -> ...                                            ....                      
letra ->  z                                         letra.x = "z"

-----------------------------------------------------------------------------

t -> p t p | p | e

t -> p F1 | e 
F1 -> t p | e 	
p -> l R1 		
R1 -> p | e 	
l -> a~z

texto -> palabra | ' ' texto | e

palabra -> 