Dada una lista de palabras se pide retornar la lista pero intercalando las
palabras desde el final y desde el inicio. 
 
Ejemplo: Hoy puede que llueva, se retorna llueva Hoy que puede.


oracion -> palara_inicio oracion palabra_final      oracion.x = palabra_inicio.x ||  oracion.x || palabra_final.x
oracion -> " "                                      oracion.x = " "
oracion -> " " palabra " "                          oracion.x = palabra.x 
oracion -> EOL                                      oracion.x = EOL

palabra_inicio -> palabra                           palabra_inicio.x = palabra.x
palabra_final -> palabra                            palabra_final.x = palabra.x
palabra_final -> " "                                palabra_final.x = " "


palabra -> palabra letra                            palabra.x = palabra.x || letra.x
palabra -> letra                                    palabra.x = letra.x

letra ->  a                                         letra.x = "a"                                       
letra ->  b                                         letra.x = "b"                          
letra -> ...                                            ....                      
letra ->  z                                         letra.x = "z"

-----------------------------------------------------------------------------
