lista -> texto                                  print(texto)

texto -> palabra " " texto palabra_final        texto.x = palabra_final.y || " " || palabra.z || texto.x
texto -> palabra                                texto.x = palabra.x
    
    
palabra_final -> " " palabra                    palabra_final.x = palabra.y || " "
palabra_final -> e                              palabra_final.x = ""
    
palabra -> palabra letra                        palabra.x = letra.y || palabra.z
palabra -> letra                                palabra.x = letra.x
    
letra -> a                                      letra.x = "a"
letra -> b                                      letra.x = "b"
    ...
letra -> z                                      letra.x = "z"
